name: Run tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - 'html/changelogs/**'
    - 'html/changelog.html'
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm
      - name: Install Tools
        run: |
          pip3 install setuptools
          bash tools/ci/install_build_tools.sh
          bash tools/ci/install_spaceman_dmm.sh dreamchecker
          pip3 install -r tools/mapmerge2/requirements.txt
      - name: Run Linters
        run: |
          bash tools/ci/check_filedirs.sh beestation.dme
          bash tools/ci/check_changelogs.sh
          find . -name "*.php" -print0 | xargs -0 -n1 php -l
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
          bash tools/ci/build_tgui.sh
          bash tools/ci/check_grep.sh
          python3 tools/mapmerge2/dmi.py --test
          ~/dreamchecker
  compile_all_maps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Compile All Maps
        run: |
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          python3 tools/ci/template_dm_generator.py
          bash tools/ci/dm.sh -DCIBUILDING -DCITESTING -DALL_MAPS beestation.dme
  auxtools_tg:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build Auxtools_tg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'willox/auxtools_tg'
          ref: '83b317412033f6ac28ac6c1ffbb08ef3d524202e'
          path: 'auxtools_tg'

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: auxtools_tg-registry-${{ hashFiles('auxtools_tg/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: auxtools_tg-index-${{ hashFiles('auxtools_tg/Cargo.lock') }}

      - name: Cache cargo build
        id: auxtools_tg-cache
        uses: actions/cache@v2
        with:
          path: auxtools_tg/target
          key: auxtools_tg-build-target-${{ hashFiles('auxtools_tg/Cargo.lock') }}

      - name: Install Ubuntu Deps
        if: steps.auxtools_tg-cache.outputs.cache-hit != 'true'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386
      - uses: actions-rs/toolchain@v1
        if: steps.auxtools_tg-cache.outputs.cache-hit != 'true'
        with:
          profile: minimal
          toolchain: ${{env.toolchain}}
          target: ${{env.target}}
          override: true

      - name: Build
        if: steps.auxtools_tg-cache.outputs.cache-hit != 'true'
        run: |
          cargo build --manifest-path auxtools_tg/Cargo.toml --target=${{env.target}} --release --verbose
          ldd auxtools_tg/target/${{env.target}}/release/libauxtools_tg.so

  auxmos:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build Auxmos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Putnam3145/auxmos'
          ref: 'master'
          path: 'auxmos'

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: auxmos-registry-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: auxmos-index-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Cache cargo build
        id: auxmos-cache
        uses: actions/cache@v2
        with:
          path: auxmos/target
          key: auxmos-build-target-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Install Ubuntu Deps
        if: steps.auxmos-cache.outputs.cache-hit != 'true'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386
      - uses: actions-rs/toolchain@v1
        if: steps.auxmos-cache.outputs.cache-hit != 'true'
        with:
          profile: minimal
          toolchain: ${{env.toolchain}}
          target: ${{env.target}}
          override: true

      - name: Build
        if: steps.auxmos-cache.outputs.cache-hit != 'true'
        run: |
          cargo build --manifest-path auxmos/Cargo.toml --target=${{env.target}} --release --verbose
          ldd auxmos/target/${{env.target}}/release/libauxmos.so

  run_all_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Setup database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE bee_ci;'
          mysql -u root -proot bee_ci < SQL/beestation_schema.sql
      - name: Install rust-g
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libssl1.1:i386
          bash tools/ci/install_rust_g.sh
      - name: Download auxtools_tg library
        uses: actions/download-artifact@v2
        with:
          name: libauxtools_tg

      - name: Download libauxmos library
        uses: actions/download-artifact@v2
        with:
          name: libauxmos
      - name: Compile and run tests
        run: |
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          bash tools/ci/dm.sh -DCIBUILDING beestation.dme
          bash tools/ci/run_server.sh
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: pwsh tools/ci/build.ps1
